### ISSUE TITLE
Create by default centos based container

### ISSUE THREAD

**Issue by jorgemoralespou** [sonatype/docker-rhel-nexus#1]
I don't think you can push our RHEL image (or any image based on it) to Dockerhub (due to legal issues) so what Red Hat usually does is create the image by default based on centos and push it to Dockerhub for easier consumption, and then have the RHEL based dockerfile so that any individual can build their own RHEL based derivative, if they can.

Here you can find an example: https://github.com/sclorg/redis-container/tree/master/3.2

**Comment by gordillo-ramon** [comment]
Regarding that, it is worth mentioning that if someone wants to test the image in origin "all-in-one" (based on CentOS), build does not work because there is no way to enable repos for building the image.

So, the usual way is, as Jorge has suggested, having 2 different Dockerfiles, one with CentOS (not supported, but ready for dev test) and another with RHEL for customers with a subscription enabled.
